name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"   # هر روز ساعت 00:00 UTC اجرا می‌شه
  workflow_dispatch:      # این خط رو حتماً بذار تا بتونی خودت دستی اجراش کنی

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-summary-cards
    permissions:
      contents: write     # این دسترسی برای نوشتن فایل‌ها در مخزن لازمه

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }} # به secretای که ساختی اشاره می‌کنه
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 8   # منطقه زمانی ایران
          AUTO_PUSH: true
